// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// httpuv.cpp
void sendWSMessage(SEXP conn, bool binary, SEXP message);
extern "C" SEXP _httpuv_sendWSMessage(SEXP conn, SEXP binary, SEXP message) {
  BEGIN_CPP11
    sendWSMessage(cpp11::as_cpp<cpp11::decay_t<SEXP>>(conn), cpp11::as_cpp<cpp11::decay_t<bool>>(binary), cpp11::as_cpp<cpp11::decay_t<SEXP>>(message));
    return R_NilValue;
  END_CPP11
}
// httpuv.cpp
void closeWS(SEXP conn, uint16_t code, std::string reason);
extern "C" SEXP _httpuv_closeWS(SEXP conn, SEXP code, SEXP reason) {
  BEGIN_CPP11
    closeWS(cpp11::as_cpp<cpp11::decay_t<SEXP>>(conn), cpp11::as_cpp<cpp11::decay_t<uint16_t>>(code), cpp11::as_cpp<cpp11::decay_t<std::string>>(reason));
    return R_NilValue;
  END_CPP11
}
// httpuv.cpp
SEXP makeTcpServer(const std::string & host, int port, sexp onHeaders, function onBodyData, function onRequest, function onWSOpen, function onWSMessage, function onWSClose, list staticPaths, list staticPathOptions, bool quiet);
extern "C" SEXP _httpuv_makeTcpServer(SEXP host, SEXP port, SEXP onHeaders, SEXP onBodyData, SEXP onRequest, SEXP onWSOpen, SEXP onWSMessage, SEXP onWSClose, SEXP staticPaths, SEXP staticPathOptions, SEXP quiet) {
  BEGIN_CPP11
    return cpp11::as_sexp(makeTcpServer(cpp11::as_cpp<cpp11::decay_t<const std::string &>>(host), cpp11::as_cpp<cpp11::decay_t<int>>(port), cpp11::as_cpp<cpp11::decay_t<sexp>>(onHeaders), cpp11::as_cpp<cpp11::decay_t<function>>(onBodyData), cpp11::as_cpp<cpp11::decay_t<function>>(onRequest), cpp11::as_cpp<cpp11::decay_t<function>>(onWSOpen), cpp11::as_cpp<cpp11::decay_t<function>>(onWSMessage), cpp11::as_cpp<cpp11::decay_t<function>>(onWSClose), cpp11::as_cpp<cpp11::decay_t<list>>(staticPaths), cpp11::as_cpp<cpp11::decay_t<list>>(staticPathOptions), cpp11::as_cpp<cpp11::decay_t<bool>>(quiet)));
  END_CPP11
}
// httpuv.cpp
SEXP makePipeServer(const std::string & name, int mask, sexp onHeaders, function onBodyData, function onRequest, function onWSOpen, function onWSMessage, function onWSClose, list staticPaths, list staticPathOptions, bool quiet);
extern "C" SEXP _httpuv_makePipeServer(SEXP name, SEXP mask, SEXP onHeaders, SEXP onBodyData, SEXP onRequest, SEXP onWSOpen, SEXP onWSMessage, SEXP onWSClose, SEXP staticPaths, SEXP staticPathOptions, SEXP quiet) {
  BEGIN_CPP11
    return cpp11::as_sexp(makePipeServer(cpp11::as_cpp<cpp11::decay_t<const std::string &>>(name), cpp11::as_cpp<cpp11::decay_t<int>>(mask), cpp11::as_cpp<cpp11::decay_t<sexp>>(onHeaders), cpp11::as_cpp<cpp11::decay_t<function>>(onBodyData), cpp11::as_cpp<cpp11::decay_t<function>>(onRequest), cpp11::as_cpp<cpp11::decay_t<function>>(onWSOpen), cpp11::as_cpp<cpp11::decay_t<function>>(onWSMessage), cpp11::as_cpp<cpp11::decay_t<function>>(onWSClose), cpp11::as_cpp<cpp11::decay_t<list>>(staticPaths), cpp11::as_cpp<cpp11::decay_t<list>>(staticPathOptions), cpp11::as_cpp<cpp11::decay_t<bool>>(quiet)));
  END_CPP11
}
// httpuv.cpp
void stopServer_(std::string handle);
extern "C" SEXP _httpuv_stopServer_(SEXP handle) {
  BEGIN_CPP11
    stopServer_(cpp11::as_cpp<cpp11::decay_t<std::string>>(handle));
    return R_NilValue;
  END_CPP11
}
// httpuv.cpp
list getStaticPaths_(std::string handle);
extern "C" SEXP _httpuv_getStaticPaths_(SEXP handle) {
  BEGIN_CPP11
    return cpp11::as_sexp(getStaticPaths_(cpp11::as_cpp<cpp11::decay_t<std::string>>(handle)));
  END_CPP11
}
// httpuv.cpp
list setStaticPaths_(std::string handle, list sp);
extern "C" SEXP _httpuv_setStaticPaths_(SEXP handle, SEXP sp) {
  BEGIN_CPP11
    return cpp11::as_sexp(setStaticPaths_(cpp11::as_cpp<cpp11::decay_t<std::string>>(handle), cpp11::as_cpp<cpp11::decay_t<list>>(sp)));
  END_CPP11
}
// httpuv.cpp
list removeStaticPaths_(std::string handle, strings paths);
extern "C" SEXP _httpuv_removeStaticPaths_(SEXP handle, SEXP paths) {
  BEGIN_CPP11
    return cpp11::as_sexp(removeStaticPaths_(cpp11::as_cpp<cpp11::decay_t<std::string>>(handle), cpp11::as_cpp<cpp11::decay_t<strings>>(paths)));
  END_CPP11
}
// httpuv.cpp
list getStaticPathOptions_(std::string handle);
extern "C" SEXP _httpuv_getStaticPathOptions_(SEXP handle) {
  BEGIN_CPP11
    return cpp11::as_sexp(getStaticPathOptions_(cpp11::as_cpp<cpp11::decay_t<std::string>>(handle)));
  END_CPP11
}
// httpuv.cpp
list setStaticPathOptions_(std::string handle, list opts);
extern "C" SEXP _httpuv_setStaticPathOptions_(SEXP handle, SEXP opts) {
  BEGIN_CPP11
    return cpp11::as_sexp(setStaticPathOptions_(cpp11::as_cpp<cpp11::decay_t<std::string>>(handle), cpp11::as_cpp<cpp11::decay_t<list>>(opts)));
  END_CPP11
}
// httpuv.cpp
std::string base64encode(const raws & x);
extern "C" SEXP _httpuv_base64encode(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(base64encode(cpp11::as_cpp<cpp11::decay_t<const raws &>>(x)));
  END_CPP11
}
// httpuv.cpp
strings encodeURI_(strings value);
extern "C" SEXP _httpuv_encodeURI_(SEXP value) {
  BEGIN_CPP11
    return cpp11::as_sexp(encodeURI_(cpp11::as_cpp<cpp11::decay_t<strings>>(value)));
  END_CPP11
}
// httpuv.cpp
strings encodeURIComponent_(strings value);
extern "C" SEXP _httpuv_encodeURIComponent_(SEXP value) {
  BEGIN_CPP11
    return cpp11::as_sexp(encodeURIComponent_(cpp11::as_cpp<cpp11::decay_t<strings>>(value)));
  END_CPP11
}
// httpuv.cpp
strings decodeURI_(strings value);
extern "C" SEXP _httpuv_decodeURI_(SEXP value) {
  BEGIN_CPP11
    return cpp11::as_sexp(decodeURI_(cpp11::as_cpp<cpp11::decay_t<strings>>(value)));
  END_CPP11
}
// httpuv.cpp
strings decodeURIComponent_(strings value);
extern "C" SEXP _httpuv_decodeURIComponent_(SEXP value) {
  BEGIN_CPP11
    return cpp11::as_sexp(decodeURIComponent_(cpp11::as_cpp<cpp11::decay_t<strings>>(value)));
  END_CPP11
}
// httpuv.cpp
int ipFamily_(const std::string & ip);
extern "C" SEXP _httpuv_ipFamily_(SEXP ip) {
  BEGIN_CPP11
    return cpp11::as_sexp(ipFamily_(cpp11::as_cpp<cpp11::decay_t<const std::string &>>(ip)));
  END_CPP11
}
// httpuv.cpp
void invokeCppCallback(SEXP data, SEXP callback_xptr);
extern "C" SEXP _httpuv_invokeCppCallback(SEXP data, SEXP callback_xptr) {
  BEGIN_CPP11
    invokeCppCallback(cpp11::as_cpp<cpp11::decay_t<SEXP>>(data), cpp11::as_cpp<cpp11::decay_t<SEXP>>(callback_xptr));
    return R_NilValue;
  END_CPP11
}
// httpuv.cpp
void getRNGState_();
extern "C" SEXP _httpuv_getRNGState_() {
  BEGIN_CPP11
    getRNGState_();
    return R_NilValue;
  END_CPP11
}
// httpuv.cpp
std::string wsconn_address(SEXP external_ptr);
extern "C" SEXP _httpuv_wsconn_address(SEXP external_ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(wsconn_address(cpp11::as_cpp<cpp11::decay_t<SEXP>>(external_ptr)));
  END_CPP11
}
// utils.cpp
std::string log_level(const std::string & level);
extern "C" SEXP _httpuv_log_level(SEXP level) {
  BEGIN_CPP11
    return cpp11::as_sexp(log_level(cpp11::as_cpp<cpp11::decay_t<const std::string &>>(level)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_httpuv_base64encode",          (DL_FUNC) &_httpuv_base64encode,           1},
    {"_httpuv_closeWS",               (DL_FUNC) &_httpuv_closeWS,                3},
    {"_httpuv_decodeURIComponent_",   (DL_FUNC) &_httpuv_decodeURIComponent_,    1},
    {"_httpuv_decodeURI_",            (DL_FUNC) &_httpuv_decodeURI_,             1},
    {"_httpuv_encodeURIComponent_",   (DL_FUNC) &_httpuv_encodeURIComponent_,    1},
    {"_httpuv_encodeURI_",            (DL_FUNC) &_httpuv_encodeURI_,             1},
    {"_httpuv_getRNGState_",          (DL_FUNC) &_httpuv_getRNGState_,           0},
    {"_httpuv_getStaticPathOptions_", (DL_FUNC) &_httpuv_getStaticPathOptions_,  1},
    {"_httpuv_getStaticPaths_",       (DL_FUNC) &_httpuv_getStaticPaths_,        1},
    {"_httpuv_invokeCppCallback",     (DL_FUNC) &_httpuv_invokeCppCallback,      2},
    {"_httpuv_ipFamily_",             (DL_FUNC) &_httpuv_ipFamily_,              1},
    {"_httpuv_log_level",             (DL_FUNC) &_httpuv_log_level,              1},
    {"_httpuv_makePipeServer",        (DL_FUNC) &_httpuv_makePipeServer,        11},
    {"_httpuv_makeTcpServer",         (DL_FUNC) &_httpuv_makeTcpServer,         11},
    {"_httpuv_removeStaticPaths_",    (DL_FUNC) &_httpuv_removeStaticPaths_,     2},
    {"_httpuv_sendWSMessage",         (DL_FUNC) &_httpuv_sendWSMessage,          3},
    {"_httpuv_setStaticPathOptions_", (DL_FUNC) &_httpuv_setStaticPathOptions_,  2},
    {"_httpuv_setStaticPaths_",       (DL_FUNC) &_httpuv_setStaticPaths_,        2},
    {"_httpuv_stopServer_",           (DL_FUNC) &_httpuv_stopServer_,            1},
    {"_httpuv_wsconn_address",        (DL_FUNC) &_httpuv_wsconn_address,         1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_httpuv(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
