// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// httpuv.cpp
void sendWSMessage(SEXP conn, bool binary, SEXP message);
extern "C" SEXP _httpuv2_sendWSMessage(SEXP conn, SEXP binary, SEXP message) {
  BEGIN_CPP4R
    sendWSMessage(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(conn), cpp4r::as_cpp<cpp4r::decay_t<bool>>(binary), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(message));
    return R_NilValue;
  END_CPP4R
}
// httpuv.cpp
void closeWS(SEXP conn, uint16_t code, std::string reason);
extern "C" SEXP _httpuv2_closeWS(SEXP conn, SEXP code, SEXP reason) {
  BEGIN_CPP4R
    closeWS(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(conn), cpp4r::as_cpp<cpp4r::decay_t<uint16_t>>(code), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(reason));
    return R_NilValue;
  END_CPP4R
}
// httpuv.cpp
SEXP makeTcpServer(const std::string & host, int port, sexp onHeaders, function onBodyData, function onRequest, function onWSOpen, function onWSMessage, function onWSClose, list staticPaths, list staticPathOptions, bool quiet);
extern "C" SEXP _httpuv2_makeTcpServer(SEXP host, SEXP port, SEXP onHeaders, SEXP onBodyData, SEXP onRequest, SEXP onWSOpen, SEXP onWSMessage, SEXP onWSClose, SEXP staticPaths, SEXP staticPathOptions, SEXP quiet) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(makeTcpServer(cpp4r::as_cpp<cpp4r::decay_t<const std::string &>>(host), cpp4r::as_cpp<cpp4r::decay_t<int>>(port), cpp4r::as_cpp<cpp4r::decay_t<sexp>>(onHeaders), cpp4r::as_cpp<cpp4r::decay_t<function>>(onBodyData), cpp4r::as_cpp<cpp4r::decay_t<function>>(onRequest), cpp4r::as_cpp<cpp4r::decay_t<function>>(onWSOpen), cpp4r::as_cpp<cpp4r::decay_t<function>>(onWSMessage), cpp4r::as_cpp<cpp4r::decay_t<function>>(onWSClose), cpp4r::as_cpp<cpp4r::decay_t<list>>(staticPaths), cpp4r::as_cpp<cpp4r::decay_t<list>>(staticPathOptions), cpp4r::as_cpp<cpp4r::decay_t<bool>>(quiet)));
  END_CPP4R
}
// httpuv.cpp
SEXP makePipeServer(const std::string & name, int mask, sexp onHeaders, function onBodyData, function onRequest, function onWSOpen, function onWSMessage, function onWSClose, list staticPaths, list staticPathOptions, bool quiet);
extern "C" SEXP _httpuv2_makePipeServer(SEXP name, SEXP mask, SEXP onHeaders, SEXP onBodyData, SEXP onRequest, SEXP onWSOpen, SEXP onWSMessage, SEXP onWSClose, SEXP staticPaths, SEXP staticPathOptions, SEXP quiet) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(makePipeServer(cpp4r::as_cpp<cpp4r::decay_t<const std::string &>>(name), cpp4r::as_cpp<cpp4r::decay_t<int>>(mask), cpp4r::as_cpp<cpp4r::decay_t<sexp>>(onHeaders), cpp4r::as_cpp<cpp4r::decay_t<function>>(onBodyData), cpp4r::as_cpp<cpp4r::decay_t<function>>(onRequest), cpp4r::as_cpp<cpp4r::decay_t<function>>(onWSOpen), cpp4r::as_cpp<cpp4r::decay_t<function>>(onWSMessage), cpp4r::as_cpp<cpp4r::decay_t<function>>(onWSClose), cpp4r::as_cpp<cpp4r::decay_t<list>>(staticPaths), cpp4r::as_cpp<cpp4r::decay_t<list>>(staticPathOptions), cpp4r::as_cpp<cpp4r::decay_t<bool>>(quiet)));
  END_CPP4R
}
// httpuv.cpp
void stopServer_(std::string handle);
extern "C" SEXP _httpuv2_stopServer_(SEXP handle) {
  BEGIN_CPP4R
    stopServer_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(handle));
    return R_NilValue;
  END_CPP4R
}
// httpuv.cpp
list getStaticPaths_(std::string handle);
extern "C" SEXP _httpuv2_getStaticPaths_(SEXP handle) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(getStaticPaths_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(handle)));
  END_CPP4R
}
// httpuv.cpp
list setStaticPaths_(std::string handle, list sp);
extern "C" SEXP _httpuv2_setStaticPaths_(SEXP handle, SEXP sp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(setStaticPaths_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(handle), cpp4r::as_cpp<cpp4r::decay_t<list>>(sp)));
  END_CPP4R
}
// httpuv.cpp
list removeStaticPaths_(std::string handle, strings paths);
extern "C" SEXP _httpuv2_removeStaticPaths_(SEXP handle, SEXP paths) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(removeStaticPaths_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(handle), cpp4r::as_cpp<cpp4r::decay_t<strings>>(paths)));
  END_CPP4R
}
// httpuv.cpp
list getStaticPathOptions_(std::string handle);
extern "C" SEXP _httpuv2_getStaticPathOptions_(SEXP handle) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(getStaticPathOptions_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(handle)));
  END_CPP4R
}
// httpuv.cpp
list setStaticPathOptions_(std::string handle, list opts);
extern "C" SEXP _httpuv2_setStaticPathOptions_(SEXP handle, SEXP opts) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(setStaticPathOptions_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(handle), cpp4r::as_cpp<cpp4r::decay_t<list>>(opts)));
  END_CPP4R
}
// httpuv.cpp
std::string base64encode(const raws & x);
extern "C" SEXP _httpuv2_base64encode(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(base64encode(cpp4r::as_cpp<cpp4r::decay_t<const raws &>>(x)));
  END_CPP4R
}
// httpuv.cpp
strings encodeURI(strings value);
extern "C" SEXP _httpuv2_encodeURI(SEXP value) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(encodeURI(cpp4r::as_cpp<cpp4r::decay_t<strings>>(value)));
  END_CPP4R
}
// httpuv.cpp
strings encodeURIComponent(strings value);
extern "C" SEXP _httpuv2_encodeURIComponent(SEXP value) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(encodeURIComponent(cpp4r::as_cpp<cpp4r::decay_t<strings>>(value)));
  END_CPP4R
}
// httpuv.cpp
strings decodeURI(strings value);
extern "C" SEXP _httpuv2_decodeURI(SEXP value) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(decodeURI(cpp4r::as_cpp<cpp4r::decay_t<strings>>(value)));
  END_CPP4R
}
// httpuv.cpp
strings decodeURIComponent(strings value);
extern "C" SEXP _httpuv2_decodeURIComponent(SEXP value) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(decodeURIComponent(cpp4r::as_cpp<cpp4r::decay_t<strings>>(value)));
  END_CPP4R
}
// httpuv.cpp
int ipFamily(const std::string & ip);
extern "C" SEXP _httpuv2_ipFamily(SEXP ip) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(ipFamily(cpp4r::as_cpp<cpp4r::decay_t<const std::string &>>(ip)));
  END_CPP4R
}
// httpuv.cpp
void invokeCppCallback(SEXP data, SEXP callback_xptr);
extern "C" SEXP _httpuv2_invokeCppCallback(SEXP data, SEXP callback_xptr) {
  BEGIN_CPP4R
    invokeCppCallback(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(data), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(callback_xptr));
    return R_NilValue;
  END_CPP4R
}
// httpuv.cpp
void getRNGState();
extern "C" SEXP _httpuv2_getRNGState() {
  BEGIN_CPP4R
    getRNGState();
    return R_NilValue;
  END_CPP4R
}
// httpuv.cpp
std::string wsconn_address(SEXP external_ptr);
extern "C" SEXP _httpuv2_wsconn_address(SEXP external_ptr) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(wsconn_address(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(external_ptr)));
  END_CPP4R
}
// utils.cpp
std::string log_level(const std::string & level);
extern "C" SEXP _httpuv2_log_level(SEXP level) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(log_level(cpp4r::as_cpp<cpp4r::decay_t<const std::string &>>(level)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_httpuv2_sendWSMessage", (DL_FUNC) &_httpuv2_sendWSMessage, 3},
    {"_httpuv2_closeWS", (DL_FUNC) &_httpuv2_closeWS, 3},
    {"_httpuv2_makeTcpServer", (DL_FUNC) &_httpuv2_makeTcpServer, 11},
    {"_httpuv2_makePipeServer", (DL_FUNC) &_httpuv2_makePipeServer, 11},
    {"_httpuv2_stopServer_", (DL_FUNC) &_httpuv2_stopServer_, 1},
    {"_httpuv2_getStaticPaths_", (DL_FUNC) &_httpuv2_getStaticPaths_, 1},
    {"_httpuv2_setStaticPaths_", (DL_FUNC) &_httpuv2_setStaticPaths_, 2},
    {"_httpuv2_removeStaticPaths_", (DL_FUNC) &_httpuv2_removeStaticPaths_, 2},
    {"_httpuv2_getStaticPathOptions_", (DL_FUNC) &_httpuv2_getStaticPathOptions_, 1},
    {"_httpuv2_setStaticPathOptions_", (DL_FUNC) &_httpuv2_setStaticPathOptions_, 2},
    {"_httpuv2_base64encode", (DL_FUNC) &_httpuv2_base64encode, 1},
    {"_httpuv2_encodeURI", (DL_FUNC) &_httpuv2_encodeURI, 1},
    {"_httpuv2_encodeURIComponent", (DL_FUNC) &_httpuv2_encodeURIComponent, 1},
    {"_httpuv2_decodeURI", (DL_FUNC) &_httpuv2_decodeURI, 1},
    {"_httpuv2_decodeURIComponent", (DL_FUNC) &_httpuv2_decodeURIComponent, 1},
    {"_httpuv2_ipFamily", (DL_FUNC) &_httpuv2_ipFamily, 1},
    {"_httpuv2_invokeCppCallback", (DL_FUNC) &_httpuv2_invokeCppCallback, 2},
    {"_httpuv2_getRNGState", (DL_FUNC) &_httpuv2_getRNGState, 0},
    {"_httpuv2_wsconn_address", (DL_FUNC) &_httpuv2_wsconn_address, 1},
    {"_httpuv2_log_level", (DL_FUNC) &_httpuv2_log_level, 1},
    {NULL, NULL, 0}
};
}
extern "C" attribute_visible void R_init_httpuv2(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
