# Generated by cpp11: do not edit by hand

sendWSMessage <- function(conn, binary, message) {
  invisible(.Call(`_httpuv_sendWSMessage`, conn, binary, message))
}

closeWS <- function(conn, code, reason) {
  invisible(.Call(`_httpuv_closeWS`, conn, code, reason))
}

makeTcpServer <- function(host, port, onHeaders, onBodyData, onRequest, onWSOpen, onWSMessage, onWSClose, staticPaths, staticPathOptions, quiet) {
  .Call(`_httpuv_makeTcpServer`, host, port, onHeaders, onBodyData, onRequest, onWSOpen, onWSMessage, onWSClose, staticPaths, staticPathOptions, quiet)
}

makePipeServer <- function(name, mask, onHeaders, onBodyData, onRequest, onWSOpen, onWSMessage, onWSClose, staticPaths, staticPathOptions, quiet) {
  .Call(`_httpuv_makePipeServer`, name, mask, onHeaders, onBodyData, onRequest, onWSOpen, onWSMessage, onWSClose, staticPaths, staticPathOptions, quiet)
}

stopServer_ <- function(handle) {
  invisible(.Call(`_httpuv_stopServer_`, handle))
}

getStaticPaths_ <- function(handle) {
  .Call(`_httpuv_getStaticPaths_`, handle)
}

setStaticPaths_ <- function(handle, sp) {
  .Call(`_httpuv_setStaticPaths_`, handle, sp)
}

removeStaticPaths_ <- function(handle, paths) {
  .Call(`_httpuv_removeStaticPaths_`, handle, paths)
}

getStaticPathOptions_ <- function(handle) {
  .Call(`_httpuv_getStaticPathOptions_`, handle)
}

setStaticPathOptions_ <- function(handle, opts) {
  .Call(`_httpuv_setStaticPathOptions_`, handle, opts)
}

base64encode <- function(x) {
  .Call(`_httpuv_base64encode`, x)
}

encodeURI_ <- function(value) {
  .Call(`_httpuv_encodeURI_`, value)
}

encodeURIComponent_ <- function(value) {
  .Call(`_httpuv_encodeURIComponent_`, value)
}

decodeURI_ <- function(value) {
  .Call(`_httpuv_decodeURI_`, value)
}

decodeURIComponent_ <- function(value) {
  .Call(`_httpuv_decodeURIComponent_`, value)
}

ipFamily_ <- function(ip) {
  .Call(`_httpuv_ipFamily_`, ip)
}

invokeCppCallback <- function(data, callback_xptr) {
  invisible(.Call(`_httpuv_invokeCppCallback`, data, callback_xptr))
}

getRNGState_ <- function() {
  invisible(.Call(`_httpuv_getRNGState_`))
}

wsconn_address <- function(external_ptr) {
  .Call(`_httpuv_wsconn_address`, external_ptr)
}

log_level <- function(level) {
  .Call(`_httpuv_log_level`, level)
}
