# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sendWSMessage <- function(conn, binary, message) {
    invisible(.Call('eventloop_sendWSMessage', PACKAGE = 'eventloop', conn, binary, message))
}

closeWS <- function(conn) {
    invisible(.Call('eventloop_closeWS', PACKAGE = 'eventloop', conn))
}

makeServer <- function(host, port, pollTimeoutMs, onRequest, onWSOpen, onWSMessage, onWSClose) {
    .Call('eventloop_makeServer', PACKAGE = 'eventloop', host, port, pollTimeoutMs, onRequest, onWSOpen, onWSMessage, onWSClose)
}

destroyServer <- function(handle) {
    invisible(.Call('eventloop_destroyServer', PACKAGE = 'eventloop', handle))
}

runOnce <- function() {
    .Call('eventloop_runOnce', PACKAGE = 'eventloop')
}

runNB <- function() {
    .Call('eventloop_runNB', PACKAGE = 'eventloop')
}

